version: '3.8'

volumes:
  seq:

services:
  userservice:
    image: localhost/talenthub.userservice.api:dev
    container_name: userservice
    environment:
      ApplicationConfiguration__ConnectionString: "Host=userdb;Database=UserServiceDb;Username=user;Password=password"
      RabbitMqConfiguration__Host: "rabbitmq"
      RabbitMqConfiguration__QueueName: "lotusbyte.talenthub.notification.req"
    depends_on:
      - userdb
      - rabbitmq
    ports:
      - "8086:8080"
    networks:
      - talenthub-net

  userdb:
    image: postgres:latest
    container_name: userdb
    environment:
      POSTGRES_DB: UserServiceDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - talenthub-net

  resumeservice:
    image: localhost/talenthub.resumeservice.api:dev
    container_name: resumeservice
    environment:
      ConnectionStrings__ResumeDb: "Host=resumedb;Database=resume;Username=user;Password=password;Search Path=resume,public"
      RabbitMQ__Host: "rabbitmq"
    depends_on:
      - resumedb
      - rabbitmq
    ports:
      - "8087:8080"
    networks:
      - talenthub-net

  resumedb:
    image: postgres:latest
    container_name: resumedb
    environment:
      POSTGRES_DB: resumedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - talenthub-net

  jobservice:
    image: localhost/talenthub.jobservice.api:dev
    container_name: jobservice
    environment:
      ConnectionStrings__JobDb: "Host=jobdb;Database=job;Username=user;Password=password;Search Path=job,public"
    depends_on:
      - jobdb
      - rabbitmq
    ports:
      - "8088:8080"
    networks:
      - talenthub-net

  jobdb:
    image: postgres:latest
    container_name: jobdb
    environment:
      POSTGRES_DB: job
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - talenthub-net

  handshakeservice:
    image: localhost/talenthub.handshakeservice.api:dev
    container_name: handshakeservice
    environment:
      ApplicationConfiguration__ConnectionString: "Host=handshakedb;Database=HandshakeServiceDb;Username=user;Password=password"
      RabbitMqConfiguration__Host: "rabbitmq"
      RabbitMqConfiguration__QueueName: "lotusbyte.talenthub.notification.req"
      UserServiceClientConfiguration__Endpoint: "http://userservice:8080/api/"
    depends_on:
      - handshakedb
      - rabbitmq
    ports:
      - "8089:8080"
    networks:
      - talenthub-net
  
  handshakedb:
    image: postgres:latest
    container_name: handshakedb
    environment:
      POSTGRES_DB: HandshakeServiceDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    networks:
      - talenthub-net

  notificationservice:
    image: localhost/talenthub.notificationservice.host:dev
    container_name: notificationservice
    environment:
      RabbitMqConfiguration__Host: "rabbitmq"
      RabbitMqConfiguration__QueueName: "lotusbyte.talenthub.notification.req"
      UserServiceClientConfiguration__Endpoint: "http://userservice:8080/api/UserSettings/"
      Seq__ServerUrl: "http://seq:5341"
    depends_on:
      - rabbitmq
      - seq
    networks:
      - talenthub-net

  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
      - seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_AUTHENTICATION: "None"
    ports:
      - 5341:5341
      - 8082:80
    networks:
      - talenthub-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - talenthub-net

networks:
  talenthub-net:
    driver: bridge
